### ISSUE TITLE
feat: add ci_local.yml workflow with go build and test steps for gemara2ampel

### ISSUE THREAD

**Issue by yvonnedevlinrh** [complytime/complytime-demos#49]
## Description

The `tools/gemara2ampel` Go module has no `go build` or `go test` step in CI. The existing `ci_checks.yml` only calls the org-wide `reusable_ci.yml` (MegaLinter), which does not catch compilation errors from dependency upgrades or test regressions.

This gap allowed breaking API changes from a transitive dependency upgrade (go-gemara v0.5.0) to go undetected until manual discovery in #48.

**Is your feature request related to a problem? Please describe.**

Every other Go repository in the complytime org that contains significant source code has a dedicated `ci_local.yml` (or equivalent) workflow that runs Go build and test steps alongside the shared `ci_checks.yml`:

- **complypack** - [`ci.yml`](https://github.com/complytime/complypack/blob/main/.github/workflows/ci.yml): `go build ./...`, `go vet ./...`, `go test -race -count=1 ./...`
- **gemara-content-service** - [`ci_local.yml`](https://github.com/complytime/gemara-content-service/blob/main/.github/workflows/ci_local.yml): `make test`, `make build`, golangci-lint
- **complytime-collector-components** - [`ci_local.yml`](https://github.com/complytime/complytime-collector-components/blob/main/.github/workflows/ci_local.yml): `task test`, golangci-lint, integration tests
- **complyctl** - [`unit_test.yml`](https://github.com/complytime/complyctl/blob/main/.github/workflows/unit_test.yml): `go test -v`

`complytime-demos` is the only Go repo missing this workflow, leaving it vulnerable to undetected build failures.

**Describe the solution you'd like**

Add a `ci_local.yml` workflow following the org convention. The `gemara-content-service` pattern is the closest fit since `complytime-demos` already has a Makefile with `build`, `test`, `vet`, and `check` targets.

The workflow should:
- Trigger on push to `main` and pull requests targeting `main`
- Set up Go using `go-version-file: tools/gemara2ampel/go.mod`
- Run `make build`, `make test`, and `make vet` (or `make check` which combines vet + fmt + test) from `tools/gemara2ampel/`
- Follow the `ci_` naming convention and least-privilege permissions model used across the org

Example structure (modeled after `gemara-content-service/ci_local.yml`):

```yaml
name: Local CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: none

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    defaults:
      run:
        working-directory: tools/gemara2ampel
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false

      - uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6.4.0
        with:
          go-version-file: tools/gemara2ampel/go.mod

      - name: Run tests
        run: make test

      - name: Build
        run: make build
```

**Describe alternatives you've considered**

- **Inline steps in `ci_checks.yml`**: Would diverge from the org pattern where `ci_checks.yml` exclusively calls `reusable_ci.yml` and repo-specific steps live in `ci_local.yml`.
- **Adding a reusable Go build/test workflow to `org-infra`**: Could be valuable long-term but adds complexity; the inline approach is simpler and matches what `complypack` and `gemara-content-service` already do.
- **Relying on MegaLinter/golangci-lint alone**: Catches lint issues but does not catch compilation errors from changed dependency APIs or test failures, as demonstrated by #48.

**Additional context**

- Related issue: #48 (build failure from go-gemara v0.5.0 breaking changes)
- The `go.work` file at the repo root includes `tools/gemara2ampel`, so the workflow needs `working-directory` set accordingly
- The existing Makefile targets: `make build` (`go build ./...`), `make test` (`go test -v ./...`), `make check` (runs `vet`, `fmt`, and `test`)
